version: '3.7'
services:
  jupiter:
    build: .
    command: jupyter notebook --ip 0.0.0.0 --allow-root --NotebookApp.token='' --NotebookApp.password='' --no-browser ControlBook.ipynb
    ports:
      - 8899:8888
    volumes:
      - .:/code
  #db:
    #image: postgres:12.0-alpine
    #ports:
      #- 5432:5432
    #volumes:
      #- postgres_data:/var/lib/postgresql/data/
      #- ./data/:/data
    #environment:
      #- POSTGRES_USER=test
      #- POSTGRES_PASSWORD=test
      #- POSTGRES_DB=test
  #clickhouse_db:
    #image: yandex/clickhouse-server
    #ports:
      #- 8123:8123
      #- 9000:9000
    #volumes:
      #- clickhouse_data:/var/lib/clickhouse yandex/clickhouse-server 
#volumes:
  #postgres_data:
  #clickhouse_data:
